In [1]:
import numpy as np

a = np.array([1, 2, 3]) # tạo mảng 1 chiều
print(type(a)) # Kiểm tra dữ liệu của a
print(a.shape) # cho biết kích thước mảng
print(a[0], a[1], a[2]) # lấy từng phần tử theo chỉ số
a[0] = 5 # Gán phần tử đầu tiên của mảng thành 5
print(a)

b = np.array([[1,2,3],[4,5,6]]) # tạo mảng 2 chiều 2x3
print(b.shape) # hình dạng mảng
print(b[0, 0], b[0, 1], b[1, 0]) 


<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


In [7]:
import numpy as np

a = np.zeros((2,2))      # tạo mảng 2 chiều 2x2,các ptu = 0
b = np.ones((1,2))       # mảng 2 chiều 1x2,các ptu = 1
c = np.full((2,2), 7)    # mảng 2 chiều 2x2,các ptu =7
d = np.eye(2)            # ma trận 2x2,đường chéo =1 và các vị trí còn lại là 0
e = np.random.random((2,2))  # tạo mảng 2 chiều có giá trị ngẫu nhiên từ 0 đến 1
print("a =\n", a)
print("\nb =\n", b)
print("\nc =\n", c)
print("\nd =\n", d)
print("\ne =\n", e)

a =
 [[0. 0.]
 [0. 0.]]

b =
 [[1. 1.]]

c =
 [[7 7]
 [7 7]]

d =
 [[1. 0.]
 [0. 1.]]

e =
 [[0.99619886 0.40183372]
 [0.48659407 0.58180634]]


In [2]:
import numpy as np
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])  # tạo mảng 2 chiều 3x4
b = a[1:2, 1:3]  # lấy mảng con từ hàng 1 đến trc hàng 2,cột 1 đến trc cột 3
print(a[0, 1])   # In phần tử hàng 0,cột 1
b[0, 0] = 77     # Gán 77 vào 0,0
print(a[0, 1])   # ...

2
2


In [8]:
import numpy as np

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])  
# mảng 2 chiều 3x4

row_r1 = a[1, :]      # lấy hàng 1 và tất cả cột
row_r2 = a[1:2, :]    # lấy h1 đến trước 2
print(row_r1, row_r1.shape)   # in
print(row_r2, row_r2.shape)   # in

col_r1 = a[:, 1]      # lấy tất cả hàng và cột thứ 1
col_r2 = a[:, 1:2]    # lấy tất cả hàng ,cột từ 1 đến trc 2
print(col_r1, col_r1.shape)   # ...
print(col_r2, col_r2.shape)   # ...

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [9]:
import numpy as np

a = np.array([[1,2], [3,4], [5,6]])   # mảng 2 chiều 3x2

print(a[[0, 1, 2], [0, 1, 0]])        # lấy 3 phần tử theo cặp .ví dụ 0,0 = 1; 1,1 = 4; 2,0 = 5

print(np.array([a[0, 0], a[1, 1], a[2, 0]]))   # tương tự như trên nhưng lấy từng phần

print(a[[0, 0], [1, 1]])              # tương tự như lấy theo cặp

print(np.array([a[0, 1], a[0, 1]]))   # ...

[1 4 5]
[1 4 5]
[2 2]
[2 2]


In [10]:
import numpy as np

a = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])   # ma trận 4x3

print(a)      # in

b = np.array([0, 2, 0, 1])   # tạo mảng b có 4 ptu

print(a[np.arange(4), b])    # lấy nhiều phần tử cùng 1 lúc

a[np.arange(4), b] += 10     # lấy 4 ô và cộng them 10

print(a)      # ...

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [11]:
import numpy as np

a = np.array([[1,2], [3,4], [5,6]])

bool_idx = (a > 2)      # so sánh từng ptu vs 2

print(bool_idx)         # 

print(a[bool_idx])      # chỉ lấy các ptu ở vị trí True trong bool

print(a[a > 2])         # viết ngắn gọn của 2 dòng trên : lọc lấy những ptu >2

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


In [12]:
import numpy as np

x = np.array([1, 2])          # cho 2 số nguyên
print(x.dtype)                # tự đặt theo kiểu int64

x = np.array([1.0, 2.0])      # ...
print(x.dtype)                # ...

x = np.array([1, 2], dtype=np.int64)   # cho 2 số kiểu int và tự gán 
print(x.dtype)                # ...

int64
float64
int64


In [13]:
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)   # ...
y = np.array([[5,6],[7,8]], dtype=np.float64)   # ...

print(x + y)                                    # ...
print(np.add(x, y))                             # ...

print(x - y)                                    # ...
print(np.subtract(x, y))                        # ...

print(x * y)                                    # ...
print(np.multiply(x, y))                        # ...

print(x / y)                                    # ...
print(np.divide(x, y))                          # ...

print(np.sqrt(x))                               # ...

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [14]:
import numpy as np

x = np.array([[1,2],[3,4]])      # ma trận 2×2
y = np.array([[5,6],[7,8]])      # ma trận 2×2
v = np.array([9,10])             # vector hàng 1×2
w = np.array([11,12])            # vector hàng 1×2

print(v.dot(w))                  # nhân vô hướng
print(np.dot(v, w))              # viết c2

print(x.dot(v))                  # 2x2 nhân 2x1
print(np.dot(x, v))              # ...

print(x.dot(y))                  # 2x2 nhân 2x2
print(np.dot(x, y))              # ...

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [15]:
import numpy as np

x = np.array([[1,2],[3,4]])   # ...

print(np.sum(x))              # cộng tất cả các ptu
print(np.sum(x, axis=0))      # cộng theo cột
print(np.sum(x, axis=1))      # cộng theo hàng

x = np.array([[1,2], [3,4]])  # ...
print(x)                      # ...
print(x.T)                    # hoán vị: đổi đường chéo

v = np.array([1,2,3])         # vecto 1 chiều
print(v)                      # ...
print(v.T)                    # 

10
[4 6]
[3 7]
[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


In [16]:
import numpy as np

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])   # ma trận 4x3
v = np.array([1, 0, 1])                                 # vecto 1x3
y = np.empty_like(x)                                    # tạo 1 ma trận mới y hệt mt 4x3 nhưng chưa có giá trị

for i in range(4):
    y[i, :] = x[i, :] + v                               # lấy hàng thứ i của x rồi cộng vecto x vào hàng đó và ghi kết quả vào hàng y

print(y)                                                # ...

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [17]:
import numpy as np

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])   # ...
v = np.array([1, 0, 1])                                 # ...
vv = np.tile(v, (4, 1))                                 # lặp lại vacto sao cho thành 4x3
print(vv)                                               # ...
y = x + vv                                              # cộng 2 ma trận 4x3
print(y)                                                # ...

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [18]:
import numpy as np
# dụng phương pháp broadcasting : mảng nhỏ hơn tự động tăng sao cho bằng mảng còn lại
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])   # ...
v = np.array([1, 0, 1])                                 # ...
y = x + v                                               # ...
print(y)                                                # ...

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [19]:
import numpy as np

# Compute outer product of vectors
v = np.array([1,2,3])          
w = np.array([4,5])            
print(np.reshape(v, (3, 1)) * w)   # biến vecto v thành v dọc (cột)

x = np.array([[1,2,3], [4,5,6]])   # ...
print(x + v)                       # thực hiện broadcasting

print(x.T + w.T)                   # 2 ma trận chuyển vị cộng nhau
print(x + np.reshape(w, (2, 1)))   # cộng w vào từng hàng của x ban đầu.

[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[ 5  9]
 [ 6 10]
 [ 7 11]]
[[ 5  6  7]
 [ 9 10 11]]


In [20]:
import numpy as np

v = np.array([1,2,3])                       
w = np.array([4,5])                         
print(np.reshape(v, (3, 1)) * w)  # biến v thành vecto 3x1           # ...

x = np.array([[1,2,3], [4,5,6]])             # ...
print(x + v)                                 # ...

print(x.T + w.T)                             # chuyển vị x thành 3x2 và w là 4,5
print(x + np.reshape(w, (2, 1)))             # biến w thành vecto cột

print(x * 2)                                 # ...

[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[ 5  9]
 [ 6 10]
 [ 7 11]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 2  4  6]
 [ 8 10 12]]
